[DEFAULT]
# Black detection parameters
black_threshold = 10
percentage_threshold = 0.95

# LED control timings in seconds
capture_delay_before = 0.1
capture_delay_after = 0.0

# GPIO configuration
chip_name = /dev/gpiochip0
uv_light_line = SODIMM_206
white_led_1_line = SODIMM_210
white_led_2_line = SODIMM_212

# Image capture parameters
image_prefix = img
image_ext = .jpg
save_folder = images

# Camera configuration
video_device = /dev/video2
video_format = YUY2
video_width = 4032
video_height = 3040
